# .github/workflows/test01.yaml
name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: playwright install
      - name: Run the PytTest script
        run: pytest -vs